version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: idea
      POSTGRES_PASSWORD: idea
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-strategy-analyzer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crypto_db
      SPRING_DATASOURCE_USERNAME: idea
      SPRING_DATASOURCE_PASSWORD: idea
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
